services:
  app:
    image: ghcr.io/e5sub/ciyuan-online:latest
    container_name: ciyuan-online
    restart: unless-stopped
    network_mode: host
    environment:
      PORT: ${PORT:-4000}
      DB_HOST: ${DB_HOST:-127.0.0.1}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-dimension_brawl}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-123456}
